# Generated by Django 3.1.14 on 2023-05-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230515_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonEntitiy',
            new_name='PokemonEntity',
        ),
    ]
